name: Sampa
url: http://sampa.cs.washington.edu

exclude: [bibble, README.md, Makefile, Dockerfile]

# use this library to parse Markdown
markdown: redcarpet
redcarpet:
    extensions: [smart, tables, with_toc_data, strikethrough]

# colorize code snippets with the pygment module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
    - {key: faculty, name: Faculty}
    - {key: staff, name: Staff}
    - {key: postdoc, name: Researchers}
    - {key: grad, name: Graduate Students}
    - {key: ugrad, name: Undergraduate Students}
    - {key: ugrad-alum, name: Past Undergraduate Students}
    - {key: collab, name: Collaborators}
    - {key: alum, name: Alumni}

# Number of news stories on the front page.
front_page_news: 4

# Base pathname for links.
base: ''

collections:
  projects:
    output: true

# Navigation bar links.
navigation:
    - title: Home
      link: /
    - title: Research
      link: /research/
    - title: Publications
      link: /publications.html

# Navigation bar links for WACAS.
nav_wacas:
    - title: Home
      link: /wacas14/
    - title: Program
      link: /wacas14/program.html

# Rewriting of old path names.
wiki_redirects:
    People: people.html
    Projects: research/
    Publications: publications.html
    EnerJ: research/approximation/enerj.html
    WebChar: research/webchar.html
    Concurrency_Bug_Detection_and_Avoidance: research/concurrencybugs.html
    Concurrency_Exceptions: research/concurrencyexceptions.html
    Deterministic_MultiProcessing_(DMP): research/dmp.html
    Grappa: research/grappa.html
    NPU: research/approximation/npu.html
    Organized_Sharing_(OSHA): research/osha.html
    Operating_System_Implications_of_Non-Volatile_Main_Memory_Systems: research/nonvolatile.html
    Support_for_Explicit_Runtime_Concurrency_Errors: research/concurrencyerrors.html
    CoreDet_License: research/coredet/license.html
    CoreDet_Source_Code: research/coredet/source.html
    Improving_Power_Efficiency_of_Web-Enabled_Mobile_Devices: research/mobileweb.html
    Seminars: seminars.html
    Funding: ''
    Main_Page: ''

# Convenient short-URL redirects.
short_urls:
    decaf: research/approximation/decaf/
